### ISSUE TITLE
Link til Lenovo PC utdatert 

### ISSUE THREAD

**Issue by Dahly96** [varianter/handbook#104]
Linken til Lenovo PCen under PC-valg i håndboken finnes ikke i sortimentet lengre, denne bør oppdateres. Ser ut som samme type finnes hvis man googler samme navn.

**Comment by mikaelbr** [comment]
Topp! Har du muligheten til å oppdatere teksten (direkte via Github her) så kan jeg godkjenne? Så unngår vi at jeg finner feil laptop

**Comment by Dahly96** [comment]
Yes, ska ordne det!

**Comment by Dahly96** [comment]
Fikk du forespørsel?

**Comment by mikaelbr** [comment]
Ser den ligger med dine lokale endringer her: https://github.com/Dahly96/handbook/tree/patch-1
Du kan gå inn på https://github.com/varianter/handbook så skal du se en boks i toppen hvor det står "Create Pull Request". Om du trykker på den skal du få opp en dialog med endringene som du kan sende. Da vil jeg fa opp forespørselen.
