### ISSUE TITLE
Link til localhost i avsnitt om "Sossis-fond"

### ISSUE THREAD

**Issue by k-ryeng** [varianter/handbook#121]
Linken til "sosiale aktiviteter utover de faste vi har satt opp" er død, den refererer til http://localhost:5000/quality_manual#sosiale-aktiviteter og er derfor ikke tilgjengelig for "utenforstående" som vurderer å søke jobb hos dere.

**Comment by mikaelbr** [comment]
Hehe. Godt fanget! Rart at folk flest ikke kjører en lokal instans av hånboka tenker jeg. Men nå er det i alle fall fikset 😬
