### ISSUE TITLE
(Veldig) liten bug i hurtignavigasjon

### ISSUE THREAD

**Issue by KreizerHgz** [varianter/handbook#147]
Hurtignavigasjon til del 1: Lederplattform - tillitsledelse under fanen "Kvalitetsrutiner" i håndboken fungerer ikke. 
href går nå til #lederplattform---tillitsledelse. Fix er å endre til #lederplattform-tillitsledelse

Hilsen overnysgjerrig jobbsøker :)

**Comment by mikaelbr** [comment]
Hei! Good catch og takk for heads-up! Skal få undersøkt det, men trolig en feil i genereringen av table of contents der.

**Comment by mikaelbr** [comment]
Skal bli fikset i https://github.com/varianter/handbook/pull/148. Takk igjen for tipset

**Comment by KreizerHgz** [comment]
Bare hyggelig :)
