### ISSUE TITLE
Redesign og spissing av landingsside

### ISSUE THREAD

**Issue by mikaelbr** [varianter/handbook#167]
Etterhvert som håndboken har vokst og vokst med innhold har vi aldri tatt oss tid til en restrukturering og et par skritt tilbake for å se om innholdet og essensen dukker opp godt nok.

Det er ulike målgrupper til håndboken:

1. Nye varianter som ikke kjenner til sine rettigheter, betingelser, rutiner, praksiser etc.
2. Erfarne varianter som vil slå opp hvordan de gjør spesifikke ting. Timeføring, utgiftsføring, hvordan gjennomføres ting som de gjør sjeldent og trenger litt påminnelse.
3. Deltakere av forskjellige teams som har oppgaver de gjør utenom det vanlige. Personalledere, sosial, fag, ledere osv.
    1. Nye i rollen som vil se hvordan ting gjennomføres.
    2. Erfarne som bruker det som arbeidsverktøy og kvalitetssikring.
4. Potensielle varianter som ønsker å se hvordan det er i Variant og hva Variant har å tilby.

Siste målgruppen er lavest prioritert men likevel viktig. Det å tilby lett konsumerbar informasjon i en oversiktsside som det første besøkende møter. Det er nyttig for å navigere igjennom alle undersidene for øvrige målgrupper og spesielt viktig for nye varianter som ikke nødvendigvis har full oversikt over alle betingelser. Vi ser at håndbok og åpen informasjon her er veldig viktig for folk som undersøker info om Variant - og det er en fint ting for alle om vi greier å være konsise nok på landingssiden til å gi en god TL;DR Variant.

## Tasks

- [ ] Initiel design og struktur (jobbes av @andreashartveit )
- [ ] Implementasjon av design (av @mikaelbr )

## Initiell forslag til struktur
![Progresjonsplan - Struktur](https://user-images.githubusercontent.com/606374/155402529-553294c7-ccbf-4497-8286-f6fd105f53e0.jpg)

**Comment by strombraaten** [comment]
Arbeidet med landingssida sees i sammenheng med #196
