### ISSUE TITLE
Søkefelt synces ikke ved nytt søk

### ISSUE THREAD

**Issue by trulshj** [varianter/handbook#179]
Hvis man først søker på noe via https://handbook.variant.no/handbook og deretter bruker det lille søkefeltet til høyre igjen så oppdateres ikke det store søkefeltet med det nye søkeordet.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/39614013/182361085-95659422-d659-458d-ad5b-25f295972bf2.png">

**Comment by trulshj** [comment]
Fixed in [4da178a7dd5ee9925d15dddf2e891d291c7b216f](https://github.com/varianter/handbook/commit/4da178a7dd5ee9925d15dddf2e891d291c7b216f)

**Comment by trulshj** [comment]
Burde kanskje løses ved å løfte state opp fra searchForm eller ved å bruke context?

**Comment by mikaelbr** [comment]
Fjernet bare hele søkefeltet i endring fra "v3" og i neste iterasjon nå endres søkeinngangen helt
