### ISSUE TITLE
Legg til global navigasjon

### ISSUE THREAD

**Issue by mikaelbr** [varianter/handbook#19]
Nå er det 3 ulike sider i håndboken men ingen måte å lenke mellom annet i teksten. Burde legge til en ny navigasjon som lar man navigere mellom sider. Tror vi må til med en redesign etterhvert, så dette kan gjøres på en enkel måte i en overgangsfase

**Comment by oddsve** [comment]
Ser bra ut, men ble den litt rar på telefon i portrait?

Odd Morten Sveås

**Comment by mikaelbr** [comment]
Bra! Fikset i #21
