### ISSUE TITLE
Skrive tekst om sommerjobb til sida om Kvalitetsrutiner/Prosesser

### ISSUE THREAD

**Issue by strombraaten** [varianter/handbook#209]
[Link til Figma](https://www.figma.com/file/E4UL8Mofye3iULcf97MP3X/Variant-H%C3%A5ndboken-3.0?node-id=1048%3A977)

Vi ser at vi snakker utfyllende om de ulike sidene av en karriere i Variant, men vi **mangler info om sommerjobb.**

Gjerne noe som beskriver hva man kan forvente som sommerjobber. Kanskje også linke til tidligere takeover-sider?

Her har vi sikkert bloggposter som kan inspirere til hva man skal skrive.

Per dags dato finnes det tekster om:
- Ansettelse og jobbintervju (selve prosessen der)
- Nyansatt - Velkommen ombord (hva som skjer før og etter oppstart)
- Personaloppfølging

**Comment by strombraaten** [comment]
Oppgava ble løst av den teksten her 
<img width="710" alt="image" src="https://user-images.githubusercontent.com/72508979/197773074-7110d145-329d-4044-af8c-c3e7ad82edef.png">

> En sommerjobb i Variant er en fin mulighet til å anvende det du har lært på skolen i praksis. Det forventes ikke at du er utlært, men at du ønsker å lære mer. I et tverrfaglig team bestående av designere og utviklere kommer du til å jobbe på et av de spennende kundeprosjektene vi har. Underveis får du god oppfølging og tilrettelegging fra erfarne konsulenter som ønsker at du skal lykkes. Sjekk ut bloggen vår for å lese mer om hva årets sommerstudenter jobbet med.
> 
> I Variant liker vi åpnenhet. Det betyr at du selvsagt ikke trenger å lure på hvordan kontrakten din vil se ut for sommeren, den ligger nemlig åpent og tilgjengelig her. Timelønnen trenger du heller ikke å lure på, den er på 271,83kr (eller 100e 🤓).

**Comment by oddsve** [comment]
Men, bør timelønn være her? Blir fort utdatert? Og hører i så fall mer hjemme på kalkulatorsiden vår.

**Comment by MartineLindstrom** [comment]
Godt poeng - tar vekk timelønn.
