### ISSUE TITLE
Synliggjøre de unike lønnsordningene vi har

### ISSUE THREAD

**Issue by mathiasflaatt** [varianter/handbook#258]
Oppdaget noe nylig at vi har noen tilfeller der lønning påvirkes utenfor lønnskalkulatoren, typ. lederlønn og daglig leder.
Jeg mener at det er en informasjon som vi burde ha i handboken i ånden av åpenhet.

**Comment by mikaelbr** [comment]
Skal være løst av https://github.com/varianter/handbook/pull/260. Lukk om du syns det er tilfredsstillende @mathiasflaatt

**Comment by mikaelbr** [comment]
Lukket sjæl jeg
