### ISSUE TITLE
Liste over ting å fikse før release av Håndbok 3.0

### ISSUE THREAD

**Issue by vegardfeste** [varianter/handbook#268]
- [x]  Denne trenger ikke være en overskrift som er med i sidemenyen. ![Skjermbilde 2023-03-15 kl  11 20 15](https://user-images.githubusercontent.com/47820591/225280125-4eaa1243-6b44-49fe-a22e-c79fb00503a0.png)

- [x] Fjerne alle store bakgrunnsblobber ref #267 

- [x] Fjerne alle gamle illustrasjoner ![Skjermbilde 2023-03-15 kl  11 21 51](https://user-images.githubusercontent.com/47820591/225280445-34740536-9795-48e0-bf47-a9b5435499ec.png)

- [x] Fikse linjedeling, skjer litt ulike plasser ![Skjermbilde 2023-03-15 kl  11 22 37](https://user-images.githubusercontent.com/47820591/225280608-29d4b509-b638-4c39-9472-bacdb9bb92ca.png)

- [ ]  Sidemeny bakgrunn er pixelert ![Skjermbilde 2023-03-15 kl  11 23 10](https://user-images.githubusercontent.com/47820591/225280731-f196f2c2-10ad-4d64-9a89-a48c56a5ca91.png)

- [ ] Søkesiden ![Skjermbilde 2023-03-15 kl  11 23 59](https://user-images.githubusercontent.com/47820591/225280950-df0b64ed-c7ff-4834-87ca-561860246015.png)

- [x]  To av linkene viser med grønn tekst ![Skjermbilde 2023-03-15 kl  11 26 46](https://user-images.githubusercontent.com/47820591/225281618-35f4f489-975a-4087-8e65-61f5a2fca37a.png)

**Comment by rompeldunk** [comment]
- [ ] Duplikat:
![image](https://user-images.githubusercontent.com/11426361/229240297-591efcdc-739c-4dbe-b445-a33a4c19ee8d.png)

- [ ] Rart med eller, eller . putt eller imellom <li> punkter
![image](https://user-images.githubusercontent.com/11426361/229241031-dab178c1-c3ea-4f30-99c9-1a69e1c9b926.png)

- [ ] Linken gir 404
![image](https://user-images.githubusercontent.com/11426361/229241583-f1b30002-443c-41b4-b248-fbafcde0073d.png)
