### ISSUE TITLE
👔 Definitionen av Gadgets

### ISSUE THREAD

**Issue by jberglund** [varianter/handbook#32]
För att förtydliga posten om gadgets i handboken så skulle vi ha tydligt definerat vad detta är och vad det betyder. Vem äger vad, vad är innanför och vad behöver vi tänka på?

Detta är nödvändigtvis inget som behöver hamna i handboken, men jag tänker det är bra att ha haft en prat runt det.

**Comment by mikaelbr** [comment]
En ting jeg mener burde med er i alle fall en liste av konkrete eksempler på hva som er blitt kjøpt på gadgetbudsjett. Slik vil det være enklere å komme frem til en avgjørelse for ansatte (og særlig nyansatte) for hva som går under tjenestlig behov

**Comment by jberglund** [comment]
I det minsta: konkreta exempel på vad som kan köpas.
