### ISSUE TITLE
Døde linker 

### ISSUE THREAD

**Issue by adriansberg** [varianter/handbook#56]
Er noen linker under [#portere-mobilabonnement](https://handbook.variant.no/information.html#portere-mobilabonnement) som skulle vært oppdatert. 

Linken til "Min side" er 404, kan kanskje erstattes med https://www.telia.no/mitt-abonnement/bytte-eier/, og linken til det delvis utfylte eierskifteskjemaet sluttet sikkert å funke i forbindelse med at delingsinnstillingene ble endret.

**Comment by adriansberg** [comment]
Også et tilfelle under [#reisetid](https://handbook.variant.no/information.html#reisetid). Nederst i seksjonen er det henvist til et avsnitt, men det avsnittet har blitt delt opp i tre avsnitt så linken går ikke til noe sted.

**Comment by mikaelbr** [comment]
Dette skal være fikset nå. Takk!
