### ISSUE TITLE
Søk på tvers av håndbøker

### ISSUE THREAD

**Issue by anders-hammervold** [varianter/handbook#95]
Har ofte behov for raskt å finne riktig tekst i håndboka. Men husker ikke nøyaktig hvilken av de, det skjer litt for ofte at jeg ikke vet hvilken det står i. Og ønsker å kunne finne det lett uten å måtte åpne alle håndbøkene.

**Comment by mikaelbr** [comment]
Ett alternativ som ofte er brukt i slike settinger er https://www.algolia.com/
